### PR TITLE
Avoid double-destroying instances

### PR DESCRIPTION
**Pull request by Meta-Maxim**
May be another solution here, but my janitors run into errors when used in the following configuration:

1. GuiModule creates a gui, adds to `guiJanitor`
2. GuiModule creates a GuiComponent class, which uses LinkToInstance to destroy the component when the component's gui is destroyed.
3. Gui class calls `guiJanitor:Cleanup()`, destroying the gui and the descendant component instance. This triggers the component class's LinkToInstance cleanup after the descendant component instance was already destroyed, resulting in an error.

As it's impossible to check if an instance has been destroyed already as opposed to just parented to nil, this change adds a pcall for only instance:Destroy() calls during cleanup.

Simple case:
```lua
local j = Janitor.new()
j:Add(workspace.p)
j:LinkToInstance(workspace.p)
workspace.p:Destroy() -- Ancestor destroyed maybe
--> `The Parent property of Workspace.p is locked`
```

### CODE REVIEW

**Comment by howmanysmall** [comment]
i actually almost added this for 1.15

**Comment by howmanysmall** [comment]
what i was thinking of doing is instead of this, making it a toggle option like i originally intended

**Comment by Meta-Maxim** [comment]
If you mean the component janitor can mark that instances may be destroyed for other reasons then that sounds better, the double-destruction error could be a useful for other designs

**Comment by Meta-Maxim** [comment]
@howmanysmall Added a toggle `.SuppressInstanceReDestroy = false -- default`

**Comment by howmanysmall** [comment]
You're gonna need to pull from the latest if you want this merged.

**Comment by Meta-Maxim** [comment]
✅

**Review by howmanysmall — CHANGES_REQUESTED** [review]
Should probably move the `    SuppressInstanceReDestroy = false;` in the Janitor table outside of it (consistency). Other than that, seems to pass the unit tests.

**Comment by howmanysmall** [comment]
Okay, sorry about the delay. Pull again and I'll finally merge.

**Comment by howmanysmall** [comment]
There you go.

**Pull request merged**
